name: TalentsCity CLI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compiling Code
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      
      with:
      
        java-version: 14
    - name: Compile code
      run: mvn compile


  test:
    runs-on: ubuntu-latest
    name: Running tests
    needs: compile
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Run unit tests
        run: mvn test
        
  build:
    runs-on: ubuntu-latest
    name: Run mvn build and generate coverage report
    needs: test
    steps:
        - name: Setup Java JDK
          uses: actions/setup-java@v1.4.3
          with:
           java-version: 14
        - name: Build with Maven
          run: mvn -B package
            
          env:
            FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
            FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
            GOOGLE_CLIENT_ID:  ${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET:  ${{ secrets.GOOGLE_CLIENT_SECRET }}
            TALENTSCITYDB_NAME:   ${{ secrets.TALENTSCITYDB_NAME }}
            TALENTSCITYDB_PASSWORD: ${{ secrets.TALENTSCITYDB_PASSWORD }}
            TALENTSCITYDB_USERNAME:   ${{ secrets.TALENTSCITYDB_USERNAME }}
